name: Benchmark

on:
  pull_request:
    paths:
    - pkg/**/*
    - cmd/**/*
    - test/**/*
    - hack/**/*
    - kustomize/**/*
    - go.mod
    - .github/workflows/benchmark.yaml
    - '!hack/releases-helm-chart.sh'
  push:
    paths:
    - pkg/**/*
    - cmd/**/*
    - test/**/*
    - hack/**/*
    - kustomize/**/*
    - go.mod
    - .github/workflows/benchmark.yaml
    - '!hack/releases-helm-chart.sh'

env:
  CGO_ENABLED: "0"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Test Benchmark
      shell: bash
      run: |
        ./hack/e2e-test.sh e2e/kwokctl/benchmark

    - name: Test Benchmark Hack
      shell: bash
      run: |
        ./hack/e2e-test.sh e2e/kwokctl/benchmark-hack

    - name: Upload logs
      uses: actions/upload-artifact@v5
      if: failure()
      with:
        name: kwok-logs-benchmark
        path: ${{ github.workspace }}/logs
